[package]
name = "monkeyc"
version = "0.1.1"
edition = "2024"
description = "A Monkey programming language implementation in Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/shahzerbaig/monkeyc"
keywords = ["monkey", "language", "compiler", "interpreter"]
categories = ["compilers", "command-line-utilities"]

[dependencies]


[build]
rustflags = ["-C", "debuginfo=2"]

[alias]
ck = "check"
cl = "clippy --all-targets --all-features"
t = "test"
b = "build"
br = "build --release"
r = "run"